### ISSUE TITLE
Deplying to android device

### ISSUE THREAD

**Issue by AndersErixon** [PolygonHive/GASP-ALS#13]
Im not sure if this is the place to do it, but deplying the original GASP works directly on my samsung s21 android device, this project fails, there are alot of rows (too many to paste into chatGPT apperently), but they end with "PackagingResults: Error: Launch failed! Unknown Error".

It do however work on the "standalone game mobile" mode, the before mentioned chatgpt seems to think its a hardware issue on my phone but I doubt that since it seems to work on the original GASP.

**Comment by PolygonHive** [comment]
I don't have an android device to test this but it's most probably related to the packaging issue that was fixed. If you have time to test again I would be interested to know it the issue was fixed.
