### ISSUE TITLE
Use Chooser instead of endless Enum Select

### ISSUE THREAD

**Issue by NickLyrick** [PolygonHive/GASP-ALS#21]
Hi. What do u think about this

![image](https://github.com/user-attachments/assets/ac2b37a6-1d11-41f1-b7ca-4abb3ffc2a3d)

Instead of this

![image](https://github.com/user-attachments/assets/31000fb5-d3f7-4bbf-915e-4a641066716c)

I can help if it's needed

Just using chooser like this

![image](https://github.com/user-attachments/assets/ae15e899-23d0-41a0-abf2-4e7389486c9b)

**Comment by craigvc** [comment]
@NickLyrick Thats awesome do you have a PR in?

**Comment by NickLyrick** [comment]
@craigvc no. I made an approach like this in my project. But I think I can make a PR for this repo too. I just don't know what u guys are thinking about this approach. 

It requires the creation of data assets for all layers. For me it's ok. But what @PolygonHive think idk

**Comment by craigvc** [comment]
I Personally like it! @NickLyrick its seems cleaner - lets see what @PolygonHive thinks

**Comment by PolygonHive** [comment]
Hey, sorry for the late answer. I actually like this as well! I will be pushing some fixes tomorrow and you can do a PR after that if you have some time :)

**Comment by NickLyrick** [comment]
@PolygonHive Okay. No Problem. If it's not too much trouble, can you tag me when I can start?

**Comment by NickLyrick** [comment]
@PolygonHive This repository can only be contributed via fork? I just can't make a push

`git push origin feature/rework-layer-selection`

```
remote: Permission to PolygonHive/GASP-ALS.git denied to NickLyrick.
fatal: unable to access 'https://github.com/PolygonHive/GASP-ALS.git/': The requested URL returned error: 403
```

**Comment by PolygonHive** [comment]
You should be able to push a branch. You just can't push to main. Let me check what's going on.

**Comment by NickLyrick** [comment]
@PolygonHive make through the fork
https://github.com/PolygonHive/GASP-ALS/pull/25

**Comment by PolygonHive** [comment]
Thanks! Will review tomorrow and merge 🫡

**Comment by PolygonHive** [comment]
Hey I am taking some time to merge this because I just made a tutorial about adding overlay states and it's using chooser so I am giving some time to people to play with it before changing the system ;) 
Also, when I add this I will mention you and your game gladly :)

**Comment by NickLyrick** [comment]
I was glad to be of help. Thanks in advance
