### ISSUE TITLE
Errors with ragdoll for the retargetted characters

### ISSUE THREAD

**Issue by emanueldev1** [PolygonHive/GASP-ALS#22]
https://github.com/user-attachments/assets/2c3987a7-1154-446f-91bc-f9b2f3463dda

I have this lag and glitch when i trigger the ragdoll on a retargeted character, how to fix it?

**Comment by craigvc** [comment]
is that the fix?
@IOchair

**Comment by PolygonHive** [comment]
Yes this fixes the issue. I will have it soon in the next update :)

**Comment by craigvc** [comment]
Ah wasnt sure if that was the fix or the issue :)

**Comment by PolygonHive** [comment]
Fixed with latest push
