### ISSUE TITLE
Duplicate two constraints to fix over rotation of the knee in the ragdoll state

### ISSUE THREAD

**Issue by IOchair** [PolygonHive/GASP-ALS#27]
![image](https://github.com/user-attachments/assets/8b55e02f-0ea0-4634-b008-0fe136ff13b9)
Copy from PA_Mannequin  and realign it to the knee position
My PR upload failed, just give the file
[PA_UEFN_Mannequin.zip](https://github.com/user-attachments/files/18048248/PA_UEFN_Mannequin.zip)

**Comment by PolygonHive** [comment]
Fixed. Thanks 👍
