### ISSUE TITLE
Right Hand Overlay Broken

### ISSUE THREAD

**Issue by moraaaaaan** [PolygonHive/GASP-ALS#5]
The right hand is not animating with unequipped items, keeps a static position even when vaulting or climbing.

**Comment by rpgjackson14** [comment]
Hello! I saw this comment on the youtube video and thought it sounded similar to the issue you are having or at least it might be correlated. I unfortunately don't have knowledge in the subject to elaborate as I am quite new. Hope this helped, have a great day.
![image](https://github.com/user-attachments/assets/d8179eec-bb0b-4dea-80c2-108a4600419d)

**Comment by PolygonHive** [comment]
This has been made better, although not perfect for now.
